name: R-CMD-check-R-release

# CI to test package on different versions of R, rel-1, rel, rel+1
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  R_LIBS_USER: /usr/local/lib/R/site-library
  LC_ALL: en_US.UTF-8
  NCPUS: 2

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    strategy:
      fail-fast: false
      matrix:
        R:
          - "4.0"
          - "4.1"
          - "4.2"
          - "4.3"
          - "4.4"
          - "4.5"

    steps:
      #check out source code
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      # rcmdcheck but do not build vignettes
      - name: Run Fast Build Check Across R Releases
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-build-vignettes"), build_args = c("--no-manual", "--no-build-vignettes"), error_on = "error")
        shell: Rscript {0}
        
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check